import type { Deal, Interaction } from "./types";

const uid = () =>
  typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : Math.random().toString(36).slice(2) + Date.now().toString(36);

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

function mkInteractions(
  list: Array<Omit<Interaction, "id">>,
): Interaction[] {
  return list.map((i) => ({ ...i, id: uid() }));
}

export function seedDeals(): Deal[] {
  return [
    {
      id: uid(),
      title: "NAC Solution Rollout",
      clientName: "Ahmed Hassan",
      clientCompany: "Jamuna Bank",
      industry: "Banking",
      dealValue: 4500000,
      currency: "BDT",
      stage: "Proposal",
      probability: 65,
      createdAt: daysAgo(25),
      expectedCloseDate: daysAhead(35),
      lastContactDate: daysAgo(3),
      assignedTo: "Me",
      competitors: ["Cisco ISE", "Aruba ClearPass"],
      products: ["Network Access Control", "Endpoint Compliance"],
      interactions: mkInteractions([
        { type: "meeting", date: daysAgo(25), notes: "Initial discovery call. Strong interest in NAC due to recent compliance audit.", sentiment: "positive", conductedBy: "Me" },
        { type: "email", date: daysAgo(18), notes: "Sent product brief and reference architecture.", sentiment: "neutral", conductedBy: "Me" },
        { type: "demo", date: daysAgo(12), notes: "Technical demo with network team. Lots of questions on AD integration.", sentiment: "positive", conductedBy: "Me" },
        { type: "proposal_sent", date: daysAgo(7), notes: "Submitted formal proposal with phased rollout pricing.", sentiment: "positive", conductedBy: "Me" },
        { type: "call", date: daysAgo(3), notes: "Champion confirmed budget exists; comparing against Cisco ISE.", sentiment: "positive", conductedBy: "Me" },
      ]),
    },
    {
      id: uid(),
      title: "Endpoint Security Renewal & Expansion",
      clientName: "Tanvir Rahman",
      clientCompany: "Square Pharmaceuticals",
      industry: "Pharmaceuticals",
      dealValue: 2800000,
      currency: "BDT",
      stage: "Negotiation",
      probability: 55,
      createdAt: daysAgo(45),
      expectedCloseDate: daysAhead(20),
      lastContactDate: daysAgo(9),
      assignedTo: "Me",
      competitors: ["CrowdStrike", "SentinelOne"],
      products: ["EDR", "MDR Service"],
      interactions: mkInteractions([
        { type: "meeting", date: daysAgo(45), notes: "Renewal discussion, expansion to manufacturing sites.", sentiment: "neutral", conductedBy: "Me" },
        { type: "demo", date: daysAgo(32), notes: "MDR service walkthrough. CFO asked about TCO.", sentiment: "neutral", conductedBy: "Me" },
        { type: "proposal_sent", date: daysAgo(20), notes: "Sent 3-year renewal proposal with MDR add-on.", sentiment: "positive", conductedBy: "Me" },
        { type: "email", date: daysAgo(14), notes: "Procurement asked for discount. Awaiting CFO sign-off.", sentiment: "neutral", conductedBy: "Me" },
        { type: "follow_up", date: daysAgo(9), notes: "Light response on follow-up. Champion travelling.", sentiment: "negative", conductedBy: "Me" },
      ]),
    },
    {
      id: uid(),
      title: "Cloud Migration Advisory",
      clientName: "Farhana Akter",
      clientCompany: "BRAC",
      industry: "Non-Profit",
      dealValue: 6200000,
      currency: "BDT",
      stage: "Discovery",
      probability: 30,
      createdAt: daysAgo(55),
      expectedCloseDate: daysAhead(60),
      lastContactDate: daysAgo(18),
      assignedTo: "Me",
      competitors: ["Accenture", "Local SI"],
      products: ["Cloud Migration", "AWS Landing Zone"],
      interactions: mkInteractions([
        { type: "meeting", date: daysAgo(55), notes: "Initial scoping call on cloud roadmap.", sentiment: "positive", conductedBy: "Me" },
        { type: "email", date: daysAgo(42), notes: "Shared discovery questionnaire.", sentiment: "neutral", conductedBy: "Me" },
        { type: "call", date: daysAgo(30), notes: "Technical alignment with IT head. Budget unclear.", sentiment: "neutral", conductedBy: "Me" },
        { type: "follow_up", date: daysAgo(18), notes: "No response to last 2 follow-ups. Internal reorg suspected.", sentiment: "negative", conductedBy: "Me" },
      ]),
    },
    {
      id: uid(),
      title: "24x7 NOC Services Contract",
      clientName: "Imran Chowdhury",
      clientCompany: "Grameenphone",
      industry: "Telecommunications",
      dealValue: 3800000,
      currency: "BDT",
      stage: "Proposal",
      probability: 75,
      createdAt: daysAgo(20),
      expectedCloseDate: daysAhead(25),
      lastContactDate: daysAgo(1),
      assignedTo: "Me",
      competitors: ["Robi Internal Team"],
      products: ["NOC Managed Services"],
      interactions: mkInteractions([
        { type: "meeting", date: daysAgo(20), notes: "Discovery on current NOC pain points. Strong appetite for outsource.", sentiment: "positive", conductedBy: "Me" },
        { type: "demo", date: daysAgo(14), notes: "SOC tooling walkthrough; client impressed with dashboards.", sentiment: "positive", conductedBy: "Me" },
        { type: "proposal_sent", date: daysAgo(8), notes: "Sent SLA-backed managed NOC proposal.", sentiment: "positive", conductedBy: "Me" },
        { type: "call", date: daysAgo(4), notes: "Procurement reviewed; minor T&C edits requested.", sentiment: "positive", conductedBy: "Me" },
        { type: "email", date: daysAgo(1), notes: "Revised SOW shared. Verbal commitment received.", sentiment: "positive", conductedBy: "Me" },
      ]),
    },
    {
      id: uid(),
      title: "WAF Solution for Public Portals",
      clientName: "Rezaul Karim",
      clientCompany: "Bangladesh Bank",
      industry: "Government / Banking",
      dealValue: 5500000,
      currency: "BDT",
      stage: "Prospecting",
      probability: 25,
      createdAt: daysAgo(12),
      expectedCloseDate: daysAhead(75),
      lastContactDate: daysAgo(5),
      assignedTo: "Me",
      competitors: ["F5", "Imperva"],
      products: ["Web Application Firewall", "DDoS Protection"],
      interactions: mkInteractions([
        { type: "email", date: daysAgo(12), notes: "Cold intro from partner. Asked for WAF capability deck.", sentiment: "neutral", conductedBy: "Me" },
        { type: "call", date: daysAgo(8), notes: "Brief intro call. Procurement is RFP-driven.", sentiment: "neutral", conductedBy: "Me" },
        { type: "meeting", date: daysAgo(5), notes: "Capability presentation to security team. Positive reception.", sentiment: "positive", conductedBy: "Me" },
      ]),
    },
    // 2 closed deals for win/loss insights
    {
      id: uid(),
      title: "SIEM Platform Deployment",
      clientName: "Nasir Uddin",
      clientCompany: "City Bank",
      industry: "Banking",
      dealValue: 7200000,
      currency: "BDT",
      stage: "Closed Won",
      probability: 100,
      createdAt: daysAgo(120),
      expectedCloseDate: daysAgo(15),
      lastContactDate: daysAgo(15),
      assignedTo: "Me",
      competitors: ["Splunk"],
      products: ["SIEM", "Threat Intel"],
      interactions: mkInteractions([
        { type: "meeting", date: daysAgo(120), notes: "Won after rigorous POC.", sentiment: "positive", conductedBy: "Me" },
      ]),
    },
    {
      id: uid(),
      title: "DLP Solution",
      clientName: "Sumi Begum",
      clientCompany: "Robi Axiata",
      industry: "Telecommunications",
      dealValue: 3200000,
      currency: "BDT",
      stage: "Closed Lost",
      probability: 0,
      createdAt: daysAgo(95),
      expectedCloseDate: daysAgo(10),
      lastContactDate: daysAgo(10),
      assignedTo: "Me",
      competitors: ["Forcepoint"],
      products: ["DLP"],
      interactions: mkInteractions([
        { type: "meeting", date: daysAgo(95), notes: "Lost to Forcepoint on price.", sentiment: "negative", conductedBy: "Me" },
      ]),
      lossReason: "Price",
    },
  ];
}
