import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useAuth } from "@/hooks/use-auth";
import { winLossAnalysis } from "@/lib/crm/ai.functions";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Loader2, RefreshCw } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/crm/insights")({
  component: InsightsPage,
});

function InsightsPage() {
  const { companyId } = useAuth();
  const [windowDays, setWindowDays] = useState("180");
  const [text, setText] = useState<string>("");
  const [count, setCount] = useState<number | null>(null);
  const fn = useServerFn(winLossAnalysis);

  const run = useMutation({
    mutationFn: () => fn({ data: { companyId: companyId!, windowDays: parseInt(windowDays, 10) } }),
    onSuccess: (r) => { setText(r.text); setCount(r.count ?? 0); },
    onError: (e: any) => toast.error(e.message ?? "Failed to analyze"),
  });

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-xl font-semibold flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary" /> Win/Loss insights</h2>
          <p className="text-sm text-muted-foreground">AI analysis of your closed deals to surface what's working — and what isn't.</p>
        </div>
        <div className="flex items-center gap-2">
          <Select value={windowDays} onValueChange={setWindowDays}>
            <SelectTrigger className="w-[160px]"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="30">Last 30 days</SelectItem>
              <SelectItem value="90">Last 90 days</SelectItem>
              <SelectItem value="180">Last 180 days</SelectItem>
              <SelectItem value="365">Last 12 months</SelectItem>
              <SelectItem value="720">Last 24 months</SelectItem>
            </SelectContent>
          </Select>
          <Button onClick={() => run.mutate()} disabled={!companyId || run.isPending}>
            {run.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : text ? <RefreshCw className="mr-2 h-4 w-4" /> : <Sparkles className="mr-2 h-4 w-4" />}
            {text ? "Regenerate" : "Generate"}
          </Button>
        </div>
      </div>

      <Card className="p-6 min-h-[300px]">
        {!text && !run.isPending && (
          <div className="flex h-[260px] flex-col items-center justify-center text-center">
            <Sparkles className="h-10 w-10 text-muted-foreground/40" />
            <p className="mt-3 text-sm text-muted-foreground max-w-md">
              Click <strong>Generate</strong> to have AI analyze every won and lost deal in the selected window and produce a coaching report with patterns, root causes, and recommendations.
            </p>
          </div>
        )}
        {run.isPending && (
          <div className="flex h-[260px] flex-col items-center justify-center text-center">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="mt-3 text-sm text-muted-foreground">Analyzing closed deals…</p>
          </div>
        )}
        {text && (
          <div className="space-y-3">
            {count != null && <Badge variant="outline">{count} closed deals analyzed</Badge>}
            <article className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap leading-relaxed">
              {text}
            </article>
          </div>
        )}
      </Card>

      <p className="text-xs text-muted-foreground">
        Insights are generated by AI based on lost_reason, competitor data, deal value, notes and cycle time. Treat as a starting point, not gospel.
      </p>
    </div>
  );
}
