/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConsultantsRouteImport } from './routes/_authenticated/consultants'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedVisitsIndexRouteImport } from './routes/_authenticated/visits.index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedVisitsNewRouteImport } from './routes/_authenticated/visits.new'
import { Route as AuthenticatedTasksReportsRouteImport } from './routes/_authenticated/tasks.reports'
import { Route as AuthenticatedTasksProjectsRouteImport } from './routes/_authenticated/tasks.projects'
import { Route as AuthenticatedTasksListRouteImport } from './routes/_authenticated/tasks.list'
import { Route as AuthenticatedTasksGanttRouteImport } from './routes/_authenticated/tasks.gantt'
import { Route as AuthenticatedTasksCalendarRouteImport } from './routes/_authenticated/tasks.calendar'
import { Route as AuthenticatedTasksBoardRouteImport } from './routes/_authenticated/tasks.board'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks.$taskId'
import { Route as AuthenticatedCrmTerritoriesRouteImport } from './routes/_authenticated/crm.territories'
import { Route as AuthenticatedCrmTemplatesRouteImport } from './routes/_authenticated/crm.templates'
import { Route as AuthenticatedCrmSettingsRouteImport } from './routes/_authenticated/crm.settings'
import { Route as AuthenticatedCrmSequencesRouteImport } from './routes/_authenticated/crm.sequences'
import { Route as AuthenticatedCrmRenewalsRouteImport } from './routes/_authenticated/crm.renewals'
import { Route as AuthenticatedCrmPipelineRouteImport } from './routes/_authenticated/crm.pipeline'
import { Route as AuthenticatedCrmLostRouteImport } from './routes/_authenticated/crm.lost'
import { Route as AuthenticatedCrmListRouteImport } from './routes/_authenticated/crm.list'
import { Route as AuthenticatedCrmInboxRouteImport } from './routes/_authenticated/crm.inbox'
import { Route as AuthenticatedCrmHotRouteImport } from './routes/_authenticated/crm.hot'
import { Route as AuthenticatedCrmForecastRouteImport } from './routes/_authenticated/crm.forecast'
import { Route as AuthenticatedCrmDashboardRouteImport } from './routes/_authenticated/crm.dashboard'
import { Route as AuthenticatedCrmCatalogRouteImport } from './routes/_authenticated/crm.catalog'
import { Route as AuthenticatedCrmAccountsRouteImport } from './routes/_authenticated/crm.accounts'
import { Route as AuthenticatedCrmLeadIdRouteImport } from './routes/_authenticated/crm.$leadId'
import { Route as ApiPublicHooksTmsOverdueScanRouteImport } from './routes/api/public/hooks/tms-overdue-scan'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'
import { Route as ApiPublicHooksCrmRenewalsRouteImport } from './routes/api/public/hooks/crm-renewals'
import { Route as AuthenticatedTasksProjectsProjectIdRouteImport } from './routes/_authenticated/tasks.projects.$projectId'
import { Route as AuthenticatedTasksProjectsProjectIdSprintsSprintIdRouteImport } from './routes/_authenticated/tasks.projects.$projectId.sprints.$sprintId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultantsRoute =
  AuthenticatedConsultantsRouteImport.update({
    id: '/consultants',
    path: '/consultants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsIndexRoute =
  AuthenticatedVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedVisitsNewRoute = AuthenticatedVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksReportsRoute =
  AuthenticatedTasksReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedTasksProjectsRoute =
  AuthenticatedTasksProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedTasksListRoute = AuthenticatedTasksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedTasksGanttRoute = AuthenticatedTasksGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedTasksCalendarRoute =
  AuthenticatedTasksCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedTasksBoardRoute = AuthenticatedTasksBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedCrmTerritoriesRoute =
  AuthenticatedCrmTerritoriesRouteImport.update({
    id: '/territories',
    path: '/territories',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmTemplatesRoute =
  AuthenticatedCrmTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmSettingsRoute =
  AuthenticatedCrmSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmSequencesRoute =
  AuthenticatedCrmSequencesRouteImport.update({
    id: '/sequences',
    path: '/sequences',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmRenewalsRoute =
  AuthenticatedCrmRenewalsRouteImport.update({
    id: '/renewals',
    path: '/renewals',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmPipelineRoute =
  AuthenticatedCrmPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLostRoute = AuthenticatedCrmLostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmListRoute = AuthenticatedCrmListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmInboxRoute = AuthenticatedCrmInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmHotRoute = AuthenticatedCrmHotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmForecastRoute =
  AuthenticatedCrmForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmDashboardRoute =
  AuthenticatedCrmDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCatalogRoute = AuthenticatedCrmCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmAccountsRoute =
  AuthenticatedCrmAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLeadIdRoute = AuthenticatedCrmLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const ApiPublicHooksTmsOverdueScanRoute =
  ApiPublicHooksTmsOverdueScanRouteImport.update({
    id: '/api/public/hooks/tms-overdue-scan',
    path: '/api/public/hooks/tms-overdue-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmRenewalsRoute =
  ApiPublicHooksCrmRenewalsRouteImport.update({
    id: '/api/public/hooks/crm-renewals',
    path: '/api/public/hooks/crm-renewals',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTasksProjectsProjectIdRoute =
  AuthenticatedTasksProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedTasksProjectsRoute,
  } as any)
const AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute =
  AuthenticatedTasksProjectsProjectIdSprintsSprintIdRouteImport.update({
    id: '/sprints/$sprintId',
    path: '/sprints/$sprintId',
    getParentRoute: () => AuthenticatedTasksProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/crm/$leadId': typeof AuthenticatedCrmLeadIdRoute
  '/crm/accounts': typeof AuthenticatedCrmAccountsRoute
  '/crm/catalog': typeof AuthenticatedCrmCatalogRoute
  '/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/crm/forecast': typeof AuthenticatedCrmForecastRoute
  '/crm/hot': typeof AuthenticatedCrmHotRoute
  '/crm/inbox': typeof AuthenticatedCrmInboxRoute
  '/crm/list': typeof AuthenticatedCrmListRoute
  '/crm/lost': typeof AuthenticatedCrmLostRoute
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/crm/renewals': typeof AuthenticatedCrmRenewalsRoute
  '/crm/sequences': typeof AuthenticatedCrmSequencesRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/templates': typeof AuthenticatedCrmTemplatesRoute
  '/crm/territories': typeof AuthenticatedCrmTerritoriesRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/board': typeof AuthenticatedTasksBoardRoute
  '/tasks/calendar': typeof AuthenticatedTasksCalendarRoute
  '/tasks/gantt': typeof AuthenticatedTasksGanttRoute
  '/tasks/list': typeof AuthenticatedTasksListRoute
  '/tasks/projects': typeof AuthenticatedTasksProjectsRouteWithChildren
  '/tasks/reports': typeof AuthenticatedTasksReportsRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/visits/': typeof AuthenticatedVisitsIndexRoute
  '/tasks/projects/$projectId': typeof AuthenticatedTasksProjectsProjectIdRouteWithChildren
  '/api/public/hooks/crm-renewals': typeof ApiPublicHooksCrmRenewalsRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/hooks/tms-overdue-scan': typeof ApiPublicHooksTmsOverdueScanRoute
  '/tasks/projects/$projectId/sprints/$sprintId': typeof AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/crm/$leadId': typeof AuthenticatedCrmLeadIdRoute
  '/crm/accounts': typeof AuthenticatedCrmAccountsRoute
  '/crm/catalog': typeof AuthenticatedCrmCatalogRoute
  '/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/crm/forecast': typeof AuthenticatedCrmForecastRoute
  '/crm/hot': typeof AuthenticatedCrmHotRoute
  '/crm/inbox': typeof AuthenticatedCrmInboxRoute
  '/crm/list': typeof AuthenticatedCrmListRoute
  '/crm/lost': typeof AuthenticatedCrmLostRoute
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/crm/renewals': typeof AuthenticatedCrmRenewalsRoute
  '/crm/sequences': typeof AuthenticatedCrmSequencesRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/templates': typeof AuthenticatedCrmTemplatesRoute
  '/crm/territories': typeof AuthenticatedCrmTerritoriesRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/board': typeof AuthenticatedTasksBoardRoute
  '/tasks/calendar': typeof AuthenticatedTasksCalendarRoute
  '/tasks/gantt': typeof AuthenticatedTasksGanttRoute
  '/tasks/list': typeof AuthenticatedTasksListRoute
  '/tasks/projects': typeof AuthenticatedTasksProjectsRouteWithChildren
  '/tasks/reports': typeof AuthenticatedTasksReportsRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/visits': typeof AuthenticatedVisitsIndexRoute
  '/tasks/projects/$projectId': typeof AuthenticatedTasksProjectsProjectIdRouteWithChildren
  '/api/public/hooks/crm-renewals': typeof ApiPublicHooksCrmRenewalsRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/hooks/tms-overdue-scan': typeof ApiPublicHooksTmsOverdueScanRoute
  '/tasks/projects/$projectId/sprints/$sprintId': typeof AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/consultants': typeof AuthenticatedConsultantsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/crm/$leadId': typeof AuthenticatedCrmLeadIdRoute
  '/_authenticated/crm/accounts': typeof AuthenticatedCrmAccountsRoute
  '/_authenticated/crm/catalog': typeof AuthenticatedCrmCatalogRoute
  '/_authenticated/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/_authenticated/crm/forecast': typeof AuthenticatedCrmForecastRoute
  '/_authenticated/crm/hot': typeof AuthenticatedCrmHotRoute
  '/_authenticated/crm/inbox': typeof AuthenticatedCrmInboxRoute
  '/_authenticated/crm/list': typeof AuthenticatedCrmListRoute
  '/_authenticated/crm/lost': typeof AuthenticatedCrmLostRoute
  '/_authenticated/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/_authenticated/crm/renewals': typeof AuthenticatedCrmRenewalsRoute
  '/_authenticated/crm/sequences': typeof AuthenticatedCrmSequencesRoute
  '/_authenticated/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/_authenticated/crm/templates': typeof AuthenticatedCrmTemplatesRoute
  '/_authenticated/crm/territories': typeof AuthenticatedCrmTerritoriesRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks/board': typeof AuthenticatedTasksBoardRoute
  '/_authenticated/tasks/calendar': typeof AuthenticatedTasksCalendarRoute
  '/_authenticated/tasks/gantt': typeof AuthenticatedTasksGanttRoute
  '/_authenticated/tasks/list': typeof AuthenticatedTasksListRoute
  '/_authenticated/tasks/projects': typeof AuthenticatedTasksProjectsRouteWithChildren
  '/_authenticated/tasks/reports': typeof AuthenticatedTasksReportsRoute
  '/_authenticated/visits/new': typeof AuthenticatedVisitsNewRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/visits/': typeof AuthenticatedVisitsIndexRoute
  '/_authenticated/tasks/projects/$projectId': typeof AuthenticatedTasksProjectsProjectIdRouteWithChildren
  '/api/public/hooks/crm-renewals': typeof ApiPublicHooksCrmRenewalsRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/hooks/tms-overdue-scan': typeof ApiPublicHooksTmsOverdueScanRoute
  '/_authenticated/tasks/projects/$projectId/sprints/$sprintId': typeof AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/check-in'
    | '/consultants'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/partners'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/crm/$leadId'
    | '/crm/accounts'
    | '/crm/catalog'
    | '/crm/dashboard'
    | '/crm/forecast'
    | '/crm/hot'
    | '/crm/inbox'
    | '/crm/list'
    | '/crm/lost'
    | '/crm/pipeline'
    | '/crm/renewals'
    | '/crm/sequences'
    | '/crm/settings'
    | '/crm/templates'
    | '/crm/territories'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/calendar'
    | '/tasks/gantt'
    | '/tasks/list'
    | '/tasks/projects'
    | '/tasks/reports'
    | '/visits/new'
    | '/crm/'
    | '/tasks/'
    | '/visits/'
    | '/tasks/projects/$projectId'
    | '/api/public/hooks/crm-renewals'
    | '/api/public/hooks/process-reminders'
    | '/api/public/hooks/tms-overdue-scan'
    | '/tasks/projects/$projectId/sprints/$sprintId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai'
    | '/check-in'
    | '/consultants'
    | '/customers'
    | '/dashboard'
    | '/partners'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/team'
    | '/crm/$leadId'
    | '/crm/accounts'
    | '/crm/catalog'
    | '/crm/dashboard'
    | '/crm/forecast'
    | '/crm/hot'
    | '/crm/inbox'
    | '/crm/list'
    | '/crm/lost'
    | '/crm/pipeline'
    | '/crm/renewals'
    | '/crm/sequences'
    | '/crm/settings'
    | '/crm/templates'
    | '/crm/territories'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/calendar'
    | '/tasks/gantt'
    | '/tasks/list'
    | '/tasks/projects'
    | '/tasks/reports'
    | '/visits/new'
    | '/crm'
    | '/tasks'
    | '/visits'
    | '/tasks/projects/$projectId'
    | '/api/public/hooks/crm-renewals'
    | '/api/public/hooks/process-reminders'
    | '/api/public/hooks/tms-overdue-scan'
    | '/tasks/projects/$projectId/sprints/$sprintId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai'
    | '/_authenticated/check-in'
    | '/_authenticated/consultants'
    | '/_authenticated/crm'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/partners'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/crm/$leadId'
    | '/_authenticated/crm/accounts'
    | '/_authenticated/crm/catalog'
    | '/_authenticated/crm/dashboard'
    | '/_authenticated/crm/forecast'
    | '/_authenticated/crm/hot'
    | '/_authenticated/crm/inbox'
    | '/_authenticated/crm/list'
    | '/_authenticated/crm/lost'
    | '/_authenticated/crm/pipeline'
    | '/_authenticated/crm/renewals'
    | '/_authenticated/crm/sequences'
    | '/_authenticated/crm/settings'
    | '/_authenticated/crm/templates'
    | '/_authenticated/crm/territories'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/board'
    | '/_authenticated/tasks/calendar'
    | '/_authenticated/tasks/gantt'
    | '/_authenticated/tasks/list'
    | '/_authenticated/tasks/projects'
    | '/_authenticated/tasks/reports'
    | '/_authenticated/visits/new'
    | '/_authenticated/crm/'
    | '/_authenticated/tasks/'
    | '/_authenticated/visits/'
    | '/_authenticated/tasks/projects/$projectId'
    | '/api/public/hooks/crm-renewals'
    | '/api/public/hooks/process-reminders'
    | '/api/public/hooks/tms-overdue-scan'
    | '/_authenticated/tasks/projects/$projectId/sprints/$sprintId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksCrmRenewalsRoute: typeof ApiPublicHooksCrmRenewalsRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
  ApiPublicHooksTmsOverdueScanRoute: typeof ApiPublicHooksTmsOverdueScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultants': {
      id: '/_authenticated/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof AuthenticatedConsultantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/': {
      id: '/_authenticated/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof AuthenticatedVisitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/visits/new': {
      id: '/_authenticated/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof AuthenticatedVisitsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/reports': {
      id: '/_authenticated/tasks/reports'
      path: '/reports'
      fullPath: '/tasks/reports'
      preLoaderRoute: typeof AuthenticatedTasksReportsRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/projects': {
      id: '/_authenticated/tasks/projects'
      path: '/projects'
      fullPath: '/tasks/projects'
      preLoaderRoute: typeof AuthenticatedTasksProjectsRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/list': {
      id: '/_authenticated/tasks/list'
      path: '/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AuthenticatedTasksListRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/gantt': {
      id: '/_authenticated/tasks/gantt'
      path: '/gantt'
      fullPath: '/tasks/gantt'
      preLoaderRoute: typeof AuthenticatedTasksGanttRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/calendar': {
      id: '/_authenticated/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof AuthenticatedTasksCalendarRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/board': {
      id: '/_authenticated/tasks/board'
      path: '/board'
      fullPath: '/tasks/board'
      preLoaderRoute: typeof AuthenticatedTasksBoardRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/crm/territories': {
      id: '/_authenticated/crm/territories'
      path: '/territories'
      fullPath: '/crm/territories'
      preLoaderRoute: typeof AuthenticatedCrmTerritoriesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/templates': {
      id: '/_authenticated/crm/templates'
      path: '/templates'
      fullPath: '/crm/templates'
      preLoaderRoute: typeof AuthenticatedCrmTemplatesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/settings': {
      id: '/_authenticated/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AuthenticatedCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/sequences': {
      id: '/_authenticated/crm/sequences'
      path: '/sequences'
      fullPath: '/crm/sequences'
      preLoaderRoute: typeof AuthenticatedCrmSequencesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/renewals': {
      id: '/_authenticated/crm/renewals'
      path: '/renewals'
      fullPath: '/crm/renewals'
      preLoaderRoute: typeof AuthenticatedCrmRenewalsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/pipeline': {
      id: '/_authenticated/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AuthenticatedCrmPipelineRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/lost': {
      id: '/_authenticated/crm/lost'
      path: '/lost'
      fullPath: '/crm/lost'
      preLoaderRoute: typeof AuthenticatedCrmLostRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/list': {
      id: '/_authenticated/crm/list'
      path: '/list'
      fullPath: '/crm/list'
      preLoaderRoute: typeof AuthenticatedCrmListRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/inbox': {
      id: '/_authenticated/crm/inbox'
      path: '/inbox'
      fullPath: '/crm/inbox'
      preLoaderRoute: typeof AuthenticatedCrmInboxRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/hot': {
      id: '/_authenticated/crm/hot'
      path: '/hot'
      fullPath: '/crm/hot'
      preLoaderRoute: typeof AuthenticatedCrmHotRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/forecast': {
      id: '/_authenticated/crm/forecast'
      path: '/forecast'
      fullPath: '/crm/forecast'
      preLoaderRoute: typeof AuthenticatedCrmForecastRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/dashboard': {
      id: '/_authenticated/crm/dashboard'
      path: '/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof AuthenticatedCrmDashboardRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/catalog': {
      id: '/_authenticated/crm/catalog'
      path: '/catalog'
      fullPath: '/crm/catalog'
      preLoaderRoute: typeof AuthenticatedCrmCatalogRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/accounts': {
      id: '/_authenticated/crm/accounts'
      path: '/accounts'
      fullPath: '/crm/accounts'
      preLoaderRoute: typeof AuthenticatedCrmAccountsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/$leadId': {
      id: '/_authenticated/crm/$leadId'
      path: '/$leadId'
      fullPath: '/crm/$leadId'
      preLoaderRoute: typeof AuthenticatedCrmLeadIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/api/public/hooks/tms-overdue-scan': {
      id: '/api/public/hooks/tms-overdue-scan'
      path: '/api/public/hooks/tms-overdue-scan'
      fullPath: '/api/public/hooks/tms-overdue-scan'
      preLoaderRoute: typeof ApiPublicHooksTmsOverdueScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-renewals': {
      id: '/api/public/hooks/crm-renewals'
      path: '/api/public/hooks/crm-renewals'
      fullPath: '/api/public/hooks/crm-renewals'
      preLoaderRoute: typeof ApiPublicHooksCrmRenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/projects/$projectId': {
      id: '/_authenticated/tasks/projects/$projectId'
      path: '/$projectId'
      fullPath: '/tasks/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedTasksProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedTasksProjectsRoute
    }
    '/_authenticated/tasks/projects/$projectId/sprints/$sprintId': {
      id: '/_authenticated/tasks/projects/$projectId/sprints/$sprintId'
      path: '/sprints/$sprintId'
      fullPath: '/tasks/projects/$projectId/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedTasksProjectsProjectIdSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedTasksProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmLeadIdRoute: typeof AuthenticatedCrmLeadIdRoute
  AuthenticatedCrmAccountsRoute: typeof AuthenticatedCrmAccountsRoute
  AuthenticatedCrmCatalogRoute: typeof AuthenticatedCrmCatalogRoute
  AuthenticatedCrmDashboardRoute: typeof AuthenticatedCrmDashboardRoute
  AuthenticatedCrmForecastRoute: typeof AuthenticatedCrmForecastRoute
  AuthenticatedCrmHotRoute: typeof AuthenticatedCrmHotRoute
  AuthenticatedCrmInboxRoute: typeof AuthenticatedCrmInboxRoute
  AuthenticatedCrmListRoute: typeof AuthenticatedCrmListRoute
  AuthenticatedCrmLostRoute: typeof AuthenticatedCrmLostRoute
  AuthenticatedCrmPipelineRoute: typeof AuthenticatedCrmPipelineRoute
  AuthenticatedCrmRenewalsRoute: typeof AuthenticatedCrmRenewalsRoute
  AuthenticatedCrmSequencesRoute: typeof AuthenticatedCrmSequencesRoute
  AuthenticatedCrmSettingsRoute: typeof AuthenticatedCrmSettingsRoute
  AuthenticatedCrmTemplatesRoute: typeof AuthenticatedCrmTemplatesRoute
  AuthenticatedCrmTerritoriesRoute: typeof AuthenticatedCrmTerritoriesRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmLeadIdRoute: AuthenticatedCrmLeadIdRoute,
  AuthenticatedCrmAccountsRoute: AuthenticatedCrmAccountsRoute,
  AuthenticatedCrmCatalogRoute: AuthenticatedCrmCatalogRoute,
  AuthenticatedCrmDashboardRoute: AuthenticatedCrmDashboardRoute,
  AuthenticatedCrmForecastRoute: AuthenticatedCrmForecastRoute,
  AuthenticatedCrmHotRoute: AuthenticatedCrmHotRoute,
  AuthenticatedCrmInboxRoute: AuthenticatedCrmInboxRoute,
  AuthenticatedCrmListRoute: AuthenticatedCrmListRoute,
  AuthenticatedCrmLostRoute: AuthenticatedCrmLostRoute,
  AuthenticatedCrmPipelineRoute: AuthenticatedCrmPipelineRoute,
  AuthenticatedCrmRenewalsRoute: AuthenticatedCrmRenewalsRoute,
  AuthenticatedCrmSequencesRoute: AuthenticatedCrmSequencesRoute,
  AuthenticatedCrmSettingsRoute: AuthenticatedCrmSettingsRoute,
  AuthenticatedCrmTemplatesRoute: AuthenticatedCrmTemplatesRoute,
  AuthenticatedCrmTerritoriesRoute: AuthenticatedCrmTerritoriesRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedTasksProjectsProjectIdRouteChildren {
  AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute: typeof AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute
}

const AuthenticatedTasksProjectsProjectIdRouteChildren: AuthenticatedTasksProjectsProjectIdRouteChildren =
  {
    AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute:
      AuthenticatedTasksProjectsProjectIdSprintsSprintIdRoute,
  }

const AuthenticatedTasksProjectsProjectIdRouteWithChildren =
  AuthenticatedTasksProjectsProjectIdRoute._addFileChildren(
    AuthenticatedTasksProjectsProjectIdRouteChildren,
  )

interface AuthenticatedTasksProjectsRouteChildren {
  AuthenticatedTasksProjectsProjectIdRoute: typeof AuthenticatedTasksProjectsProjectIdRouteWithChildren
}

const AuthenticatedTasksProjectsRouteChildren: AuthenticatedTasksProjectsRouteChildren =
  {
    AuthenticatedTasksProjectsProjectIdRoute:
      AuthenticatedTasksProjectsProjectIdRouteWithChildren,
  }

const AuthenticatedTasksProjectsRouteWithChildren =
  AuthenticatedTasksProjectsRoute._addFileChildren(
    AuthenticatedTasksProjectsRouteChildren,
  )

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksBoardRoute: typeof AuthenticatedTasksBoardRoute
  AuthenticatedTasksCalendarRoute: typeof AuthenticatedTasksCalendarRoute
  AuthenticatedTasksGanttRoute: typeof AuthenticatedTasksGanttRoute
  AuthenticatedTasksListRoute: typeof AuthenticatedTasksListRoute
  AuthenticatedTasksProjectsRoute: typeof AuthenticatedTasksProjectsRouteWithChildren
  AuthenticatedTasksReportsRoute: typeof AuthenticatedTasksReportsRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksBoardRoute: AuthenticatedTasksBoardRoute,
  AuthenticatedTasksCalendarRoute: AuthenticatedTasksCalendarRoute,
  AuthenticatedTasksGanttRoute: AuthenticatedTasksGanttRoute,
  AuthenticatedTasksListRoute: AuthenticatedTasksListRoute,
  AuthenticatedTasksProjectsRoute: AuthenticatedTasksProjectsRouteWithChildren,
  AuthenticatedTasksReportsRoute: AuthenticatedTasksReportsRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedConsultantsRoute: typeof AuthenticatedConsultantsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedVisitsNewRoute: typeof AuthenticatedVisitsNewRoute
  AuthenticatedVisitsIndexRoute: typeof AuthenticatedVisitsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedConsultantsRoute: AuthenticatedConsultantsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedVisitsNewRoute: AuthenticatedVisitsNewRoute,
  AuthenticatedVisitsIndexRoute: AuthenticatedVisitsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksCrmRenewalsRoute: ApiPublicHooksCrmRenewalsRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
  ApiPublicHooksTmsOverdueScanRoute: ApiPublicHooksTmsOverdueScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
