name: Test GCP Host

on:
  workflow_dispatch:

jobs:
  test-host:
    runs-on: ubuntu-latest

    steps:
      - name: Check GCP Host
        run: |
          if [ -z "${{ secrets.GCP_HOST }}" ]; then
            echo "GCP_HOST is empty"
            exit 1
          else
            echo "GCP_HOST is configured"
          fi
